### PR TITLE
Define _chol! for FSA's

### PR DESCRIPTION
**Pull request by mschauer**
Addresses #128 by defining _chol! for FixedSizeArrays and adding some needed predicates

### CODE REVIEW

**Comment by c42f** [comment]
Looks good to me.

Why do we have the in place version by the way? FSAs can't provide the in place semantics...

**Comment by mschauer** [comment]
FSAs here are treated the same way as numbers. `chol` calls `_chol!` and even recursively `_chol!` on the elements. Immutables like for example numbers or FSA set therefore `_chol! = chol`. All clear? :-)

**Comment by c42f** [comment]
Ah, I see `chol!` isn't exported, it's an implementation detail.

**Comment by SimonDanisch** [comment]
Thanks!

**Pull request merged**
