### PR TITLE
expm for real Mat{3,3}

### PR DESCRIPTION
**Pull request by mschauer**
The bad news is that the accuracy using putzers formula is much worse then julia's expm. The good news is

```
julia> @time @repeat 10^5 expm(B)
  0.027290 seconds (100.00 k allocations: 7.629 MB)

julia> @time @repeat 10^5 expm(A)
  0.937276 seconds (3.30 M allocations: 343.323 MB, 2.70% gc time)
```

Please have a look everybody. @SimonDanisch do you now why eye is so slow?

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Hm, the current version is really slow indeed.
I got it to be twice as slow as julia's `eye`, but somethings still goes wrong with the inlining of map, even though I use `Expr(:meta, :inline)`.
When I manually inline it, its twice as fast (probably even faster) as julia's `eye`...

**Comment by mschauer** [comment]
I know how to do the nonsymmetric case. If you have time, how would you go to implement

```
function rotate3!(A, c, s, i,j)
    for k in 1:3
        aik = A[i,k]
        ajk = A[j,k]
        A[i,k] = aik * c + ajk * s
        A[j,k] = ajk * c - aik * s
    end
    A
end
```

for immutable Mat{3,3,T}? Otherwise I figure it out.

**Comment by SimonDanisch** [comment]
you could try `A = setindex(A, val, i,j)`  and see if llvm is smart enough to actually remove the overhead of it.

**Comment by mschauer** [comment]
It did not work. I found

```
macro rotate3(A, c, s, i,j)
  l = setdiff(1:3, [i,j])[1]
  codeblock([
        quote
             $(symbol("a",l,k)) = $(esc(A))[$l,$k]
             $(symbol("a",i,k))  = $(esc(A))[$i,$k] * $(esc(c)) + $(esc(A))[$j,$k] * $(esc(s))
             $(symbol("a",j,k))  = $(esc(A))[$j,$k] * $(esc(c)) - $(esc(A))[$i,$k] * $(esc(s))
        end
        for k in 1:3]...,        quote Mat(((a11,a21,a31),(a12,a22,a32),(a13,a23,a33))) end
    )
end
```

this is not nice, but for now it does the trick.

**Comment by SimonDanisch** [comment]
What's `codeblock`? But that looks like the best solution with the current tools.

**Comment by mschauer** [comment]
codeblock is just aggregating statements as in https://github.com/lindahua/Devectorize.jl/blob/46bc6f8107eb09e3b9433a334d742b2fcdaeee13/src/meta_tools.jl .

**Comment by mschauer** [comment]
I implemented the nonsymmetric case. I have still to check if the test fails because of inaccuracy of due to a bug.

**Comment by mschauer** [comment]
These are pathological cases, so it is no problem to exceptionally call lapack if the qr does not converge fastly. That makes fixing this easy without affecting speed in general..

**Comment by mschauer** [comment]
PR ready for feedback!

**Comment by SimonDanisch** [comment]
coverage seems to be broken at the moment, so I'm not sure if you haven't already added enough tests;) rest looks pretty awesome, as far as I can tell =)

**Comment by mschauer** [comment]
Well, here you go.

**Comment by SimonDanisch** [comment]
Marvelous! Seems like `Coverage.jl` is also functioning again!

**Comment by SimonDanisch** [comment]
Thanks a lot for the effort!

**Comment by SimonDanisch** [comment]
Hm... seems like it has sporadic errors ~~on Win32~~!? This wasn't failing before, right?

```
> expm(Mat{3,3}) 
      Failure :: (line:-1) :: expm(Mat{3,3}) :: fact was false 
        Expression: norm(sort([FixedSizeArrays.eigvalssym(Mat(m))...]) - sort(eigvals(m))) <= 1.0e-9 --> true 
          Expected: true 
          Occurred: false 
      Failure :: (line:-1) :: expm(Mat{3,3}) :: fact was false 
        Expression: norm(Matrix(expm(Mat(m))) - expm(m)) <= 1.0e-9 --> true 
          Expected: true 
          Occurred: false
```

**Comment by mschauer** [comment]
I am looking into it. The error can be of order sqrt(eps()), maybe 1e-9 is too optimistic.

**Pull request merged**
