### PR TITLE
fix matmul

### PR DESCRIPTION
**Pull request by mschauer**
Adresses #38 partially

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Pushing to your PR doesn't seem to work :D 
Can you remove the old `Mat * FixedVector` method? Vec is okay for now, and for the general case we want to do this a little cleaner in the future!

**Comment by mschauer** [comment]
I know these are preliminary implementations. These small fixes are mostly what I need now to make FixedSizeArrays useful for my purposes, the surprise is rather how far I get with what we have now.

**Comment by SimonDanisch** [comment]
I'm actually not that heavily invested in linear algebra (only the subset I need for graphics), so I'm very happy about your contributions! :)

**Comment by mschauer** [comment]
great, then there will be some more

**Pull request merged**
