### PR TITLE
Operations with UniformScaling

### PR DESCRIPTION
**Pull request by mschauer**
plus test

### CODE REVIEW

**Comment by mschauer** [comment]
(This is the first part of #49)

**Comment by mschauer** [comment]
Closes #37

**Comment by mschauer** [comment]
Can we shortlist this, I'd like to use it in a subsequent PR? Thx!

**Comment by SimonDanisch** [comment]
You mean merge? Sure, I didn't merge it right away because of the coverage and then forgot about it :D 
But I can surely merge this!

**Comment by SimonDanisch** [comment]
Thanks :)

**Pull request merged**
