### PR TITLE
more stable calculation of putzer coefficient r3

### PR DESCRIPTION
**Pull request by mschauer**
I rewrote 

```
r3 = (-((y  - z)*exp(x*t) + (z - x)*exp(t*y ) + (x - y )*exp(t*z)) / ((x - y )*(y  - z)*(z - x)))
= ((exp(x*t)-exp(t*z))/(x-z)-(exp(t*z)-exp(t*y))/(z-y))/(x-y)
```

and added a function to calculate the latter. Hopefully this solves the problems. The code is now cleaner too.

### CODE REVIEW

**Comment by mschauer** [comment]
@SimonDanisch AppVeyor ran the old test, can you rerun the tests please?

```
expm(Mat{3,3}) 
      Failure :: (line:-1) :: expm(Mat{3,3}) :: fact was false 
        Expression: norm(sort([FixedSizeArrays.eigvalssym(Mat(m))...]) - sort(eigvals(m))) <= 1.0e-9 --> true 
          Expected: true 
          Occurred: false 
      Failure :: (line:-1) :: expm(Mat{3,3}) :: fact was false 
        Expression: norm(Matrix(expm(Mat(m))) - expm(m)) <= 1.0e-9 --> true 
          Expected: true 
          Occurred: false
```

**Comment by SimonDanisch** [comment]
The appveyor file is wrong... We could just merge it and I fix it seperately.

**Comment by mschauer** [comment]
Yes. By the way, I am quite happy that this code ended up here. It originates from an earlier attempt of implementing this functionality in c which ended nowhere. One nice thing is that because it is julia, it works with BigFloat-Mat's or other julia types. Computing matrix exponentials up to `1.e-76` precision is quite something, not at all possible with a wrapper around `expm` of base.

```
julia> norm(Matrix(expm(Mat(big([0.0 0.0 1.0; -1.0 1.0 0.0; -1.0 0.0 2.0])))) - big([-0.0 0.0  1.0; -0.5  1.0  -0.5; -1.0  0.0  2.0])*e,1)
1.036340226611333355046362223536047948533920043732353766202844416420231016379491e-76
```

**Comment by SimonDanisch** [comment]
Great to hear!
I have big hopes for julia because of these things ;)

**Pull request merged**
