### PR TITLE
Sd/no 

### PR DESCRIPTION
**Pull request by SimonDanisch**
needs some benchmarks!

### CODE REVIEW

**Comment by andyferris** [comment]
This is cool - makes a lot of sense to me!

Sometimes I wonder if we should go a step further and just implement linear algebra on bare `NTuple`s. Kind of like what `Base.Linalg` does for `Base.Array`. You have a very clear definition of what is a multi-dimensional tuple, even.

**Comment by SimonDanisch** [comment]
Thanks :)

> Sometimes I wonder if we should go a step further and just implement linear algebra on bare NTuples

Yeah would make sense... There are several pro and cons to that, which I've evaluated at some point... We should re-evaluate a second time when we rewrite for 0.5!
But I think it's unlikely that we'll use pure tuples for this, since most people won't like  to have `Base.Tuple <: AbstractArray` ... But we can have `Vec{N, T} _::NTuple{N, T} end` and then use that!

**Comment by SimonDanisch** [comment]
I started creating a BenchmarkSuite which didn't record any slow downs for this, so I guess we can merge!

**Comment by andyferris** [comment]
> most people won't like to have Base.Tuple <: AbstractArray

Now that is something I hadn't considered before... interesting... 

The benchmark suite sounds like a good idea!

**Pull request merged**
