### PR TITLE
map refactoring for different eltypes and different FSA subtypes.

### PR DESCRIPTION
**Pull request by c42f**
~~WIP - do not merge!~~

I started some work in an attempt to address some of the FSA type interoperability woes (see #104, #63, #93, #82, etc).  The initial code here is modification of the `map()` infrastructure to allow the output FSA type to be specified as part of the mapping operation. I'm not even sure this is the right thing yet, but the general idea for the next step is to add some `Base.promote_op()`-like infrastructure to allow operations like `v1 .< v2` to specify an output of Vec{N,Bool} when `v1` and `v2` are `Vec{N,Float64}` or whatever.

Something like `promote_op` seems to be required to fix `point + vec -> point`, but deducing the correct output for elementwise ops like `v1 .< v2` with `v1,v2 <: Vec` might be doable via normal type inference over the resulting tuple, I'm not sure.  (Eg, `Vec(1 < 2, 3.0 < 4)` returns a `Vec{2,Bool}` as you want).

### CODE REVIEW

**Comment by c42f** [comment]
Oh, by the way - 4 of the tests fail due to obscure problems with `@inferred` in this PR.  Not sure how to fix that yet.

**Comment by SimonDanisch** [comment]
Thanks a lot for taking a stab at it! Sadly, the `@inferred` test is pretty important.... My last rewrites went to the trash can because of it ;) I can take a look at it!

**Comment by SimonDanisch** [comment]
``` Julia
a = Vec(3.2f0)
@code_warntype 0.2+a
Variables:
  x::Float64
  y::FixedSizeArrays.Vec{1,Float32}
  ##T#7681::Type{Float64}
  #######s2#7649#7679#7682::Type{FixedSizeArrays.Vec{1,Float32}}
  #######s1#7650#7680#7683::Type{Float64}

Body:
  begin 
      $(Expr(:meta, :inline)) # /home/s/.julia/v0.4/FixedSizeArrays/src/ops.jl, line 66:
      ##T#7681 = Float64
      return x::Float64 + (FixedSizeArrays.map)($(Expr(:new, FixedSizeArrays.ConstructTypeFun{Float64})),(top(apply_type))((top(getfield))((top(getfield))(FixedSizeArrays.Main,:FixedSizeArrays)::Any,:Vec)::Any,1,Float64)::Any,y::FixedSizeArrays.Vec{1,Float32})::Any::Any
  end::Any
```

That seems to be the problem! Looks fixable :)

**Comment by c42f** [comment]
Awesome, thanks for having a look.  That's about as far as I got before getting distracted by other things.  Hope to get back to it this weekend, I'm super happy to have any suggestions on how to fix it though :)

**Comment by SimonDanisch** [comment]
``` Julia
8801 facts verified.
show for subtype
1 fact verified.
INFO: FixedSizeArrays tests passed
```

:) 

Let me include a few improvements that I've been working on as well!

**Comment by c42f** [comment]
I added your commit to fix the type inference problems.  I don't really claim to understand what went wrong here, but quite honestly the previous `similar` implementation seemed like a huge hack so I'm not too surprised something went haywire ;-)  I was impressed you managed to pull it off at all given that `TypeName` seems generally resistant to introspection with the usual tools!

**Comment by SimonDanisch** [comment]
Cool, that also works!
I think even `@generated` gets an inference pass to make it more predictable than a pure `eval`, so the parse must have had really terrible implications.
If there wasn't something weird going on and not enough time to investigate, I would never had used parse in the first place ;)

**Comment by c42f** [comment]
Sure, I was impressed you managed to make it work, even if it was a bit disgusting :-)

One design problem to consider is where exactly type promotion to the output type should happen. 
1. On the one hand, we might want some of it in `map()` for _elementwise_ operations.  Could, for instance, `map(+, Vec(1,2), Vec(1.0,2.0))` deduce an output type of `Vec{2,Float64}` even though `+` is not a functor?  @andyferris has suggested we emit code looking like `Vec((F(arg1[1],arg2[1]), F(arg1[2],arg2[2])))` which would work for the case of `Vec`.  Thinking as I write here - I didn't know how to generate a call to the correct generic constructor.  Suppose, for example, you had

``` julia
immutable MyVec{T,GeographicDatum} <: FixedArray{T,1,(3,)}
    x::T
    y::T
    z::T
end
```

Then how does `map(+, MyVec{Float64,WGS84Datum}(1,2,3), MyVec{Int,WGS84Datum}(1.0,2.0,3.0))` promote "correctly" to `MyVec{Float64,WGS84Datum}`?  I guess `promote_rule` might be it, though that seems more for plain numeric types in Base, I dunno.  Consider

``` julia
promote_rule{T1,T2,Datum}(::Type{MyVec{T1,Datum}}, ::Type{MyVec{T2,Datum}})
    = MyVec{promote_type(T1,T2),Datum}
```

But I guess this won't work for operations which "demote" the types instead, such as comparisons, ugh.  Oh, maybe it's some kind of dual-argument form of the current `constructor_expr()`:

``` julia
constructor_expr{T1,T2,Datum}(::Type{MyVec{T1,Datum}}, ::Type{MyVec{T2,Datum}}, tuple_expr::Expr) = :(MyVec(Datum, $tuple_expr...))
```

Could work I guess, with a simple default which would no doubt work for `Vec`, `Mat`, and most other custom FSAs which don't have extra type parameters.
1. On the other hand, for mixed operations like `point + vec`, the promotion rules act on the types of the whole vectors themselves, (eg `Point{2,Int}` and `Vec{2,Float64}` in this case) rather than just the element types.  This kind of promotion also needs the operation (`+` in the example).  At this stage I think we can leave this for a separate PR.

**Comment by SimonDanisch** [comment]
Would it make sense to make it:

``` Julia
immutable MyVec{T<:Datum} <: FixedArray{T,1,(3,)}
    x::T
    y::T
    z::T
end
```

I wanted to ban additional type parameters, since they seem avoidable and add quite a few problems...

**Comment by c42f** [comment]
The idea with the `Datum` above is to tag the physical measurement procedure for a point (eg, from a surveying measurement), and you want points with different `Datum` tags to be not directly comparable. So `T <: Datum` doesn't really make sense.  I'm not sure it's required for FixedSizeArrays to support this pattern, it's just something we've been thinking about a lot lately in Geodesy.jl so it's on my mind.

In general it does seem like the user might want to add, remove or otherwise reorder the type parameters of `FixedArray` in their custom subtype.  Is this basically meant to be unsupported in the current FSA design?  I think it's probably possible, but might be a bit of work to support.

**Comment by c42f** [comment]
I'm getting closer on this.  Things which work:

Much improved type inference for binary and unary operations (ie, anything implemented with `map()`) #104 #63 #82 

``` julia
julia> real(Point(1+im,2+2im))
Point(1,2)

julia> Vec(1.0,2.0) / 100
Vec(0.01,0.02)

julia> Vec(1.0im,2.0im) .* Vec(1,2)
Vec(0.0 + 1.0im,0.0 + 4.0im)

julia> Vec(1.5,1.5) .< Vec(1,2)
Vec(false,true)
```

Mixed FixedArray and AbstractArray arithmetic (an added bonus)

```
julia> eye(Mat{2,2,Float64}) + [1 2; 3 4]
FixedSizeArrays.Mat{2,2,Float64}(
    2.0 2.0
    3.0 5.0
)
```

Still need to add some tests and do some additional cleanup though.  I'm worried there's some overlap between what I've done so far and existing constructor code.

BTW, with julia version 0.4.5 I find that one of the tests in `typeinf.jl` is failing on master, due to the inexact way that we search for `Any` in the test there (it's an Any which is optimized out, so a bogus failure).

**Comment by SimonDanisch** [comment]
by the way (to my embarrassment) I just recently learned, that the map I implemented in `FixedSizeArrays` is much rather `broadcast`. I never fully realized what broadcast does due to its weird name ;) So if you want, feel free to refactor a bit...If not, I might refactor this myself later on!

**Comment by c42f** [comment]
It doesn't seem exactly like broadcast to me -

``` julia
# On master
julia> a = Mat(((1,2),))
FixedSizeArrays.Mat{2,1,Int64}(
    1
    2
)


julia> b = Mat(((1,),(2,)))
FixedSizeArrays.Mat{1,2,Int64}(
    1 2
)

# Should result in 2x2 matrix for broadcast.  On my branch this is now a `DimensionMismatch`.
julia> map(+, a,b)
2-element Array{Any,1}:
 2
 4
```

I'd say the FSA `map()` is broadcast-like only in that it broadcasts `Number` across a given FSA (so I guess you're right, it's not `map()`, but neither is it `broadcast()`!).  One problem with trying to implement a generic `broadcast()` is that it makes the non-concrete nature of `FixedArray` even harder to deal with: what is the definitive output type when broadcast increases the dimensionality of the original arrays?

This is sort of a fundamental problem with the whole design of subtyping `FixedArray` rather than it being a concrete type.  Some of the problems would go away if we had a `typealias` which instead of aliasing created an entirely new type.  That way you could get `Point` and `Vec` to be different types in the type system but with the same representation, but it still wouldn't let us name the fields as in FixedVectorNoTuple...

**Comment by SimonDanisch** [comment]
But it's more similar in the behaviour...I'm wondering, if we should worry that it's neither of them. I find it quite natural to mix scalars with arrays in map, but I'm not sure if others would agree. This question becomes especially relevant, when we want to inherit from `DenseArray`.

Basetype and similar should solve our issue with changing the type parameters... We just need to make the implementation more generic! ;)

**Comment by c42f** [comment]
Yes, for implementing dotted operators `broadcast()` is definitely the right thing and the current behavior for scalars is broadcast and not map.  I'll have a think about how much work this would be.

**Comment by c42f** [comment]
Had just a little time to think about this today and prototype a bit.

Deducing the output type is the major problem with implementing broadcast if we want to allow mixing `FixedArray` with `AbstractArray` in a nice way.

For `broadcast()`, mixing the two must result in a normal Array, since the output size will only be known at runtime so we can't know the output FSA type.  (The output size of a broadcast may also be really large in which case using an FSA would be pretty terrible anyway.)

Say you want to broadcast `.+`.  There's only really one set of rules which makes sense:

```
Number .+ FSA -> FSA
FSA .+ FSA -> FSA
FSA .+ AbstractArray -> AbstractArray
```

For `map()` it's natural to assume that mixing the two should result in a `FixedArray`, because you've already got a fixed array of the same size, and you can have the following set of rules:

```
Number + FSA -> FSA
FSA + FSA -> FSA
FSA + AbstractArray -> FSA
```

So it's a sticky situation.  On the one hand, we should follow the usual broadcast semantics from `AbstractArray`.  On the other hand, these play havoc with the ability to make `FixedArray` and `AbstractArray` interoperate efficiently, with a minimum of intrusive syntax. 

At this stage, I'm inclined to punt on `broadcast()` and just get this PR merged, as it will fix a whole bunch of problems.  Just a few more tests to write I think, and it should be good to go.

**Comment by c42f** [comment]
@SimonDanisch I think this all works now and I've got various tests.  I've no idea about the coveralls failures, it appears to be complaining about coverage reduction on the only lines in mapreduce.jl which I didn't touch.

A note about some API changes.  Here we have
- A new variant of `map()` which takes the output type as the second argument.  The purpose of this is to allow future promote_op infrastructure (#102) and to allow the user to specify the output container type if desired.  However, it's not strictly required right now so it could be removed if desired.
- A new function `construct_similar(::Type{FSA}, nested_tuple)` for use in constructing FSAs which are in the "same family" as a given FSA (eg, all `Vec`s), but with possibly different eltype and size as deduced from an initialization tuple.  (In principle, this might arguably be a method of `similar()` instead, but passing a tuple as initialization clashes with the `Base` convention of passing a tuple as the size parameter.)

@andyferris @awbsmith FYI I think this is done and will help your use cases a bit, comments welcome.

**Comment by c42f** [comment]
Huh, it's hard to take coveralls seriously when a patch which strictly adds additional tests supposedly causes the test coverage to _decrease_!

**Comment by SimonDanisch** [comment]
Thanks for the brainstorm, this is something which will definitely be annoying to deal with! So lets get this merged first  ;)

**Comment by SimonDanisch** [comment]
Great! Thanks a lot for this major effort! Don't worry too much about coverage, it's always a bit unpredictable. The reduce part was not hit previously and somehow my last PR effected it to be hit, no idea why and why not anymore ;)

**Comment by SimonDanisch** [comment]
Okay looks good! I'll play around with it a bit and conduct some benchmarks and then merge this :)

**Comment by c42f** [comment]
Thanks!  How do you currently go about benchmarking?  The `bench` directory doesn't seem to have a lot in it.

**Comment by SimonDanisch** [comment]
yeah, they're also very old... I use [BenchmarkTools](https://github.com/JuliaCI/BenchmarkTools.jl) together with `@code_llvm` and will need to write some new benchmarks!

**Comment by SimonDanisch** [comment]
Okay this looks pretty good! :) feel free to merge!

**Comment by c42f** [comment]
Done, thanks for looking over it :-)

**Comment by awbsmith** [comment]
Looks good - and with map handling promotions I can clean up the overloads for bilndot in [PR #98](https://github.com/SimonDanisch/FixedSizeArrays.jl/pull/98) which makes me happy.

**Pull request merged**
